<a href="https://colab.research.google.com/github/Adityasaharan04/Data-Mining/blob/main/LAB_5_DM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:
arr = np.array([1, 2, 3], dtype=float)
print(arr.dtype)


float64


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.dtype)


(2, 3)
6
int64


In [11]:
arr1 = np.zeros((2,3))
arr2 = np.ones((3,3))
arr3 = np.arange(1, 10, 2)
arr4 = np.linspace(1, 10, 5)


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[1:4])


30
[20 30 40]


In [6]:
arr = np.array([1, 2, 3])
print(arr + 10)


[11 12 13]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr):
    print(x, end=" ")


1 2 3 4 5 6 

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [9]:
# Importing NumPy
import numpy as np

# Creating NumPy arrays
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Checking data type
print("Data type:", arr.dtype)

# Creating different types of arrays
zeros_arr = np.zeros((2,3))  # 2x3 matrix filled with zeros
ones_arr = np.ones((3,3))    # 3x3 matrix filled with ones
range_arr = np.arange(1, 10, 2)  # Array with a step of 2

print("Zeros Array:\n", zeros_arr)
print("Ones Array:\n", ones_arr)
print("Range Array:", range_arr)

# Indexing and Slicing
arr2 = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr2[2])
print("Slicing from index 1 to 4:", arr2[1:4])

# Broadcasting
arr3 = np.array([1, 2, 3])
print("Broadcasting Example:", arr3 + 10)

# Iterating Over an Array
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print("Iterating over array:")
for x in np.nditer(arr4):
    print(x, end=" ")

# Array Operations
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])

print("\nAddition:", arr5 + arr6)
print("Multiplication:", arr5 * arr6)
print("Division:", arr5 / arr6)


Array: [1 2 3 4 5]
Data type: int64
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range Array: [1 3 5 7 9]
Element at index 2: 30
Slicing from index 1 to 4: [20 30 40]
Broadcasting Example: [11 12 13]
Iterating over array:
1 2 3 4 5 6 
Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
